display_ascii_art = true

[key]
  always_prompt_delete = false
  always_prompt_glob_delete = true
  always_prompt_overwrite = false
  always_encrypt = false

[store]
  default_store_name = "store"
  always_prompt_delete = true
  always_prompt_overwrite = true

[list]
  always_show_all_stores = true
  default_list_format = "table"
  always_show_full_values = false
  always_hide_header = false
  default_columns = "meta,ttl,size,store,key,value"

[git]
  auto_fetch = false
  auto_commit = true
  auto_push = false
  default_commit_message = "{{ summary }}"
