[colors.primary]
background = '#101418'
foreground = '#e0e2e8'

[colors.selection]
text = '#e0e2e8'
background = '#0e4a73'

[colors.cursor]
text = '#101418'
cursor = '#9bcbfb'

[colors.normal]
black   = '#101418'
red     = '#ff729c'
green   = '#7dfb8e'
yellow  = '#fff772'
blue    = '#81b7ee'
magenta = '#224b74'
cyan    = '#9bcbfb'
white   = '#eff7ff'

[colors.bright]
black   = '#969da3'
red     = '#ff9fbc'
green   = '#a5ffb1'
yellow  = '#fffaa5'
blue    = '#acd5ff'
magenta = '#badcff'
cyan    = '#d3e9ff'
white   = '#f8fbff'
