[colors.primary]
background = '#131315'
foreground = '#e5e2e3'

[colors.selection]
text = '#e5e2e3'
background = '#444654'

[colors.cursor]
text = '#131315'
cursor = '#c4c5d6'

[colors.normal]
black   = '#131315'
red     = '#f66e90'
green   = '#6bd67d'
yellow  = '#ffd872'
blue    = '#b6b7cb'
magenta = '#535463'
cyan    = '#c4c5d6'
white   = '#d3d4e0'

[colors.bright]
black   = '#80818b'
red     = '#ff9fb6'
green   = '#a5ffb5'
yellow  = '#ffe6a5'
blue    = '#dadbeb'
magenta = '#eff0ff'
cyan    = '#f5f5ff'
white   = '#f8f9ff'
