[colors.primary]
background = '#121413'
foreground = '#e3e2e0'

[colors.selection]
text = '#e3e2e0'
background = '#3b4a42'

[colors.cursor]
text = '#121413'
cursor = '#bacbc0'

[colors.normal]
black   = '#121413'
red     = '#e98d69'
green   = '#65cb67'
yellow  = '#fdef72'
blue    = '#adc0b4'
magenta = '#4f5d54'
cyan    = '#bacbc0'
white   = '#c8d5cc'

[colors.bright]
black   = '#7a837d'
red     = '#ffba9f'
green   = '#9ef39f'
yellow  = '#fff6a5'
blue    = '#cfdfd5'
magenta = '#f0fff5'
cyan    = '#f5fff8'
white   = '#f8fffa'
