-- stylua: ignore
local palette = {
  none        = "NONE",
  bg          = "#3b224c",
  fg          = "#a4a0e8",
  white       = "#ffffff",
  lilac       = "#dbbfef",
  bossanova   = "#452859",
  midnight    = "#3b224c",
  revolver    = "#281733",
  silver      = "#cccccc",
  sirocco     = "#697C81",
  comet       = "#5a5977",
  mint        = "#9ff28f",
  almond      = "#eccdba",
  chamois     = "#E8DCA0",
  honey       = "#efba5d",
  lightning   = "#ffcd1c",
  apricot     = "#f47868",
  delta       = "#6F44F0",
  blue        = "#61afef",
  diff_plus   = "#35bf86",
  diff_minus  = "#f22c86",
  selection   = "#540099",
}

local function apply_highlights(highlights)
  for name, value in pairs(highlights) do
    vim.api.nvim_set_hl(0, name, value)
  end
end

local function load()
  if vim.fn.exists("syntax_on") == 1 then
    vim.cmd("hi clear")
    vim.cmd.syntax("reset")
  end

  vim.o.background = "dark"
  vim.o.termguicolors = true
  vim.g.colors_name = "me"

  -- stylua: ignore
  local highlights = {
    Normal                                      = { fg = palette.fg, bg = palette.bg },
    NormalNC                                    = { link = "Normal" },
    NormalFloat                                 = { fg = palette.fg, bg = palette.revolver },
    Title                                       = { fg = palette.white, bg = palette.none },
    Cursor                                      = { fg = palette.bg, bg = palette.white },
    CursorIM                                    = { link = "Cursor" },
    lCursor                                     = { link = "Cursor" },
    CursorLine                                  = { fg = palette.none, bg = palette.bossanova },
    ColorColumn                                 = { link = "CursorLine" },
    CursorLineNr                                = { fg = palette.white, bg = palette.none },
    Conceal                                     = { fg = palette.sirocco, bg = palette.none },
    CursorColumn                                = { link = "CursorLine" },
    Directory                                   = { fg = palette.blue, bg = palette.none },
    DiffAdd                                     = { fg = palette.revolver, bg = palette.mint },
    DiffChange                                  = { fg = palette.lightning, bg = palette.none },
    DiffDelete                                  = { fg = palette.bossanova, bg = palette.apricot },
    DiffText                                    = { fg = palette.revolver, bg = palette.lightning },
    DiffAdded                                   = { fg = palette.mint },
    DiffRemoved                                 = { fg = palette.apricot },
    DiffChanged                                 = { fg = palette.blue },
    DiffOldFile                                 = { fg = palette.lightning },
    DiffNewFile                                 = { link = "DiffAdded" },
    DiffFile                                    = { link = "DiffChanged" },
    DiffLine                                    = { fg = palette.bossanova },
    DiffIndexLine                               = { fg = palette.diff_plus },
    ErrorMsg                                    = { fg = palette.apricot, bg = palette.none },
    WinSeparator                                = { fg = palette.bossanova, bg = palette.none },
    Folded                                      = { fg = palette.sirocco, bg = palette.none },
    FoldColumn                                  = { fg = palette.none, bg = palette.none },
    IncSearch                                   = { fg = palette.lightning, bg = palette.sirocco },
    CurSearch                                   = { link = "IncSearch" },
    LineNr                                      = { fg = palette.sirocco, bg = palette.none },
    NonText                                     = { link = "LineNr" },
    Pmenu                                       = { fg = palette.white, bg = palette.revolver },
    PmenuSel                                    = { fg = palette.none, bg = palette.bossanova },
    PmenuSbar                                   = { fg = palette.none, bg = palette.revolver },
    PmenuThumb                                  = { fg = palette.none, bg = palette.white },
    Question                                    = { fg = palette.delta, bg = palette.none },
    QuickFixLine                                = { fg = palette.revolver, bg = palette.lightning },
    Search                                      = { fg = palette.revolver, bg = palette.lightning },
    SignColumn                                  = { link = "FoldColumn" },
    SpecialKey                                  = { link = "LineNr" },
    SpellBad                                    = { undercurl = true },
    SpellCap                                    = { link = "SpellBad" },
    SpellLocal                                  = { link = "SpellBad" },
    SpellRare                                   = { link = "SpellBad" },
    StatusLine                                  = { fg = palette.white, bg = palette.bossanova },
    StatusLineNC                                = { fg = palette.sirocco, bg = palette.none },
    StatusLineTerm                              = { link = "StatusLine" },
    StatusLineTermNC                            = { fg = palette.bossanova, bg = palette.none },
    StatusInactive                              = { fg = palette.bossanova, bg = palette.bg },
    StatusNormal                                = { fg = palette.bossanova, bg = palette.blue },
    StatusInsert                                = { fg = palette.bossanova, bg = palette.mint },
    StatusVisual                                = { fg = palette.bossanova, bg = palette.delta },
    StatusReplace                               = { fg = palette.bossanova, bg = palette.diff_minus },
    StatusCommand                               = { fg = palette.bossanova, bg = palette.honey },
    StatusTerminal                              = { link = "StatusInsert" },
    WinBar                                      = { fg = palette.fg, bg = palette.bg },
    WinBarNC                                    = { fg = palette.sirocco, bg = palette.bg },
    TabLine                                     = { link = "LineNr" },
    TabLineSel                                  = { fg = palette.white, bg = palette.none },
    TabLineFill                                 = { fg = palette.none, bg = palette.revolver },
    Terminal                                    = { link = "Pmenu" },
    Visual                                      = { fg = palette.none, bg = palette.selection },
    VisualNOS                                   = { fg = palette.fg, bg = palette.none },
    WarningMsg                                  = { fg = palette.lightning, bg = palette.none },
    WildMenu                                    = { fg = palette.revolver, bg = palette.blue },
    EndOfBuffer                                 = { fg = palette.bg, bg = palette.none },
    FloatBorder                                 = { fg = palette.fg, bg = palette.bg },
    MatchParen                                  = { fg = palette.none, bg = palette.comet },
    -- Syntax
    Comment                                     = { fg = palette.sirocco, bg = palette.none },
    Constant                                    = { fg = palette.white, bg = palette.none },
    String                                      = { fg = palette.silver, bg = palette.none },
    Character                                   = { fg = palette.honey, bg = palette.none },
    Number                                      = { fg = palette.chamois, bg = palette.none },
    Boolean                                     = { fg = palette.almond, bg = palette.none },
    Float                                       = { link = "Number" },
    Identifier                                  = { fg = palette.fg, bg = palette.none },
    Function                                    = { fg = palette.white, bg = palette.none },
    Statement                                   = { fg = palette.almond, bg = palette.none },
    Conditional                                 = { link = "Statement" },
    Repeat                                      = { link = "Statement" },
    Label                                       = { link = "Statement" },
    Operator                                    = { fg = palette.white, bg = palette.none },
    Keyword                                     = { fg = palette.almond, bg = palette.none, bold = true },
    Exception                                   = { link = "Statement" },
    PreProc                                     = { fg = palette.lilac, bg = palette.none },
    Include                                     = { link = "Statement" },
    Define                                      = { link = "Statement" },
    Macro                                       = { link = "PreProc" },
    PreCondit                                   = { link = "PreProc" },
    Type                                        = { fg = palette.white, bg = palette.none },
    StorageClass                                = { link = "Type" },
    Structure                                   = { link = "Type" },
    Typedef                                     = { link = "Type" },
    Special                                     = { fg = palette.lilac, bg = palette.none },
    SpecialChar                                 = { link = "Special" },
    Tag                                         = { link = "Statement" },
    Delimiter                                   = { link = "Identifier" },
    SpecialComment                              = { link = "Comment" },
    Debug                                       = { fg = "#634450", bg = palette.none },
    Error                                       = { fg = palette.apricot, bg = palette.none },
    Ignore                                      = { link = "Comment" },
    Underlined                                  = { fg = palette.white, bg = palette.none },
    Todo                                        = { link = "Comment" },
    -- LSP/Diagnostics
    DiagnosticError                             = { fg = palette.apricot },
    DiagnosticHint                              = { fg = palette.silver },
    DiagnosticInfo                              = { fg = palette.delta },
    DiagnosticWarn                              = { fg = palette.lightning },
    DiagnosticInformation                       = { fg = palette.delta, bold = true },
    DiagnosticTruncateLine                      = { fg = palette.fg, bold = true },
    DiagnosticUnderlineError                    = { sp = palette.apricot, undercurl = true },
    DiagnosticUnderlineHint                     = { link = "DiagnosticUnderlineError" },
    DiagnosticUnderlineInfo                     = { link = "DiagnosticUnderlineError" },
    DiagnosticUnderlineWarn                     = { link = "DiagnosticUnderlineError" },
    LspCodeLens                                 = { fg = palette.comet },
    LspCodeLensSeparator                        = { link = "LspCodeLens" },
    LspDiagnosticsFloatingError                 = { link = "DiagnosticError" },
    LspDiagnosticsFloatingHint                  = { link = "DiagnosticHint" },
    LspDiagnosticsFloatingInformation           = { link = "DiagnosticInfo" },
    LspDiagnosticsFloatingWarn                  = { link = "DiagnosticWarn" },
    LspFloatWinBorder                           = { fg = palette.revolver },
    LspFloatWinNormal                           = { fg = palette.fg, bg = palette.revolver },
    LspInlayHint                                = { link = "Comment" },
    LspReferenceText                            = { fg = palette.none, bg = palette.bg },
    LspReferenceRead                            = { link = "LspReferenceText" },
    LspReferenceWrite                           = { link = "LspReferenceText" },
    ProviderTruncateLine                        = { fg = palette.fg },
    ["@lsp.type.builtinType"]                   = { link = "Type" },
    ["@lsp.type.keyword"]                       = { link = "Keyword" },
    ["@lsp.type.operator"]                      = { link = "Operator" },
    ["@lsp.type.property"]                      = { link = "Operator" },
    ["@lsp.type.parameter"]                     = { link = "Identifier" },
    ["@lsp.type.variable"]                      = { link = "Identifier" },
    ["@lsp.typemod.enumMember.defaultLibrary"]  = { link = "Constant" },
    ["@lsp.typemod.function.defaultLibrary"]    = { link = "Function" },
    ["@lsp.typemod.function.global"]            = { link = "Function" },
    ["@lsp.typemod.method.defaultLibrary"]      = { link = "Function" },
    ["@lsp.typemod.method.reference"]           = { link = "Function" },
    ["@lsp.typemod.method.trait"]               = { link = "Function" },
    ["@lsp.typemod.selfKeyword.defaultLibrary"] = { fg = palette.mint, bg = palette.none },
    ["@lsp.typemod.variable.defaultLibrary"]    = { link = "Identifier" },
    ["@lsp.typemod.variable.readonly"]          = { link = "Constant" },
    ["@lsp.type.macro"]                         = { link = "PreProc" },
}

  apply_highlights(highlights)
end

load()

return load
