set -Ux XDG_DESKTOP_DIR "$HOME/"
set -Ux XDG_DOWNLOAD_DIR "$HOME/downloads"
set -Ux XDG_TEMPLATES_DIR "$HOME/"
set -Ux XDG_PUBLICSHARE_DIR "$HOME/"
set -Ux XDG_DOCUMENTS_DIR "$HOME/documents"
set -Ux XDG_MUSIC_DIR "$HOME/music"
set -Ux XDG_PICTURES_DIR "$HOME/pictures"
set -Ux XDG_VIDEOS_DIR "$HOME/videos"
